Repository sous-chefs/yum-epel, pull requests merged in 2021-11, with the labels that each got.

#74 Add support for CentOS Stream 8
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  attributes/default.rb
  attributes/epel-next-debuginfo.rb
  attributes/epel-next-source.rb
  attributes/epel-next-testing-debuginfo.rb
  attributes/epel-next-testing-source.rb
  attributes/epel-next-testing.rb
  attributes/epel-next.rb
  attributes/epel.rb
  kitchen.dokken.yml
  kitchen.yml
  libraries/helpers.rb
  spec/default_spec.rb
  test/integration/all/all_spec.rb
  test/integration/default/default_spec.rb
Labels: Release: Minor

#75 Restore epel and epel-debuginfo into the default list for Stream
  CHANGELOG.md
  attributes/epel.rb
  libraries/helpers.rb
  spec/default_spec.rb
  test/integration/all/all_spec.rb
  test/integration/default/default_spec.rb
Labels: Bug, Release: Patch

#76 Update documentation for epel on CentOS Stream
  CHANGELOG.md
  README.md
Labels: Release: Patch

#77 Rename helper method to epel_8_repos to not conflict with yum-centos
  CHANGELOG.md
  attributes/default.rb
  libraries/helpers.rb
Labels: Release: Patch
